name: Build with PyInstaller
on: [push]

jobs:
  # Build with PyInstaller
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        CONFIG: ["3.10", "3.9"]
        PLATFORM: ["x64"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Build
      uses: sayyid5416/pyinstaller@v1
      with: 
        spec: "main.py"
        python_arch: ${{matrix.PLATFORM}}
        python_ver: ${{matrix.CONFIG}}

  # Unit Test
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
      - name: Lint with flake8
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          conda install pytest
          pytest